name: Labeler
on:
  pull_request_target:

jobs:
  label:
    name: Labeler
    runs-on: ubuntu-latest
    steps:

    - uses: actions/labeler@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true

    - uses: actions/labeler@main
      if: "github.event.type == 'closed' && github.event.pull_request.merged == true"
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler_merged.yml
        sync-labels: true
